import type { ClientProfile } from './stores/financial-store';

export interface TestProfile {
  id: string;
  label: string;
  description: string;
  profile: ClientProfile;
}

export const TEST_PROFILES: TestProfile[] = [
  {
    id: 'first-timer',
    label: 'Sarah - First Timer',
    description: 'No properties, starting from scratch',
    profile: {
      personal: {
        firstName: 'Sarah',
        email: 'sarah.chen@example.com',
        phone: '0412 345 678',
        age: 28,
        state: 'VIC',
        dependents: 0,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 85000,
        employmentType: 'payg-fulltime',
        yearsInRole: 3,
        hasHecsHelp: true,
        hecsBalance: 28000,
      },
      financial: {
        cashSavings: 45000,
        monthlyExpenses: 4600,
        existingDebts: [
          { type: 'hecs', balance: 28000 },
        ],
        borrowingCapacity: 450000,
        hasBroker: false,
        hasPreApproval: false,
        creditCardLimits: 5000,
      },
      portfolio: {
        ownsHome: false,
        investmentProperties: [],
        totalEquity: 0,
      },
      goals: {
        primaryGoal: 'first-property',
        goalDetail: 'Buy first investment property within 12 months',
        timeHorizon: '10-plus-years',
        riskTolerance: 'moderate',
        strategyPreference: 'unsure',
        nextStepTimeline: 'Next 6-12 months',
        budgetForNextPurchase: 450000,
      },
      locationPrefs: {
        preferredStates: ['VIC'],
        openToInterstate: true,
        proximityPreference: 'Metro and major regional',
      },
      taxAndStructure: {
        marginalTaxRate: '32.5',
        hasAccountant: false,
        hasSolicitor: false,
        existingStructures: [],
      },
      experience: {
        investingExperience: 'some-knowledge',
        biggestChallenge: 'Not sure where to start or what type of property to look for',
      },
      summary: 'Sarah is a 28-year-old first-time investor based in Victoria, earning $85k/year as a PAYG employee. She has $45k in savings but no existing properties or equity. Her borrowing capacity is around $450k. She has a $28k HECS debt. She wants to buy her first investment property within the next 12 months and is open to interstate purchases. She has a moderate risk tolerance and a long-term horizon of 10+ years but is unsure whether to focus on growth or cash flow.',
      agentBriefs: {
        baselineBen: 'Sarah is a first-time investor based in VIC, 28 years old, earning $85k PAYG full-time. She has $45k savings, $450k borrowing capacity, and a $28k HECS debt. No existing properties. Her goal is to buy her first investment property within 12 months. She has a moderate risk tolerance with a 10+ year horizon but is unsure on strategy - needs guidance on whether to pursue growth or cash flow. No broker, no accountant, no pre-approval yet. Her biggest challenge is knowing where to start.',
        finderFred: 'Sarah is looking to buy her first investment property within the next 6-12 months. Budget is around $450k based on borrowing capacity. She has $45k cash for deposit. Based in VIC but open to interstate for the right deal. Prefers metro and major regional areas. No strategy preference yet - needs guidance on property type and location. No existing portfolio. PAYG on $85k, moderate risk tolerance.',
        investorCoach: 'Sarah earns $85k/year PAYG full-time, 3 years in role. No existing properties - this will be her first investment purchase. $45k cash savings, $4,600/month expenses. $28k HECS debt reducing borrowing capacity. Total borrowing capacity $450k. No broker or pre-approval yet. $5k credit card limit. No other income streams. Goal is to build a portfolio over 10+ years starting with first purchase in the next 12 months. Moderate risk tolerance, unsure on growth vs cash flow strategy.',
        dealSpecialist: 'Sarah has no existing ownership structures - no trusts, companies, or SMSF. She is on the 32.5% marginal tax rate ($85k income). No accountant or solicitor engaged. No financial planner. This is her first property purchase so structure decisions are being made from scratch. No dependents, not investing with a partner. No insurance considerations yet as no portfolio exists.',
      },
      completenessScore: 78,
      dataGaps: ['partnerIncome', 'otherIncomeStreams', 'hasFinancialPlanner', 'interestedInStructuring'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'growing-portfolio',
    label: 'James - Growing Portfolio',
    description: '2 properties, $180k equity, scaling up',
    profile: {
      personal: {
        firstName: 'James',
        email: 'james.mitchell@example.com',
        phone: '0423 456 789',
        age: 35,
        state: 'VIC',
        dependents: 2,
        partnerInvesting: true,
        partnerIncome: 75000,
      },
      employment: {
        grossAnnualIncome: 130000,
        employmentType: 'payg-fulltime',
        yearsInRole: 6,
        hasHecsHelp: true,
        hecsBalance: 12000,
        otherIncomeStreams: 'Rental income from 2 investment properties',
        otherIncomeAmount: 54000,
      },
      financial: {
        cashSavings: 85000,
        monthlyExpenses: 6500,
        existingDebts: [
          { type: 'hecs', balance: 12000 },
          { type: 'car-loan', balance: 18000, monthlyRepayment: 450 },
        ],
        borrowingCapacity: 720000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 15000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 850000,
        homeMortgage: 520000,
        investmentProperties: [
          {
            location: 'Brunswick, VIC',
            type: 'unit-apartment',
            currentValue: 620000,
            mortgageOwing: 480000,
            weeklyRent: 520,
            ownershipStructure: 'personal',
            yearPurchased: 2021,
            purchasePrice: 545000,
          },
          {
            location: 'Geelong, VIC',
            type: 'house',
            currentValue: 485000,
            mortgageOwing: 390000,
            weeklyRent: 410,
            ownershipStructure: 'joint-personal',
            yearPurchased: 2023,
            purchasePrice: 460000,
          },
        ],
        totalEquity: 180000,
      },
      goals: {
        primaryGoal: 'grow-portfolio',
        goalDetail: 'Scale to 5 properties in the next 3 years using equity recycling',
        timeHorizon: '3-5-years',
        riskTolerance: 'growth',
        strategyPreference: 'capital-growth',
        nextStepTimeline: 'Next 6 months',
        budgetForNextPurchase: 550000,
      },
      locationPrefs: {
        preferredStates: ['VIC', 'QLD'],
        preferredRegions: ['South-east QLD', 'Geelong corridor'],
        openToInterstate: true,
        proximityPreference: 'Metro and major regional',
      },
      taxAndStructure: {
        marginalTaxRate: '37',
        hasAccountant: true,
        hasSolicitor: false,
        existingStructures: ['personal', 'joint-personal'],
        interestedInStructuring: true,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 3,
        biggestChallenge: 'Not sure how to access equity without selling',
        specificQuestionsForToday: 'Want to understand trust structures for future acquisitions',
      },
      summary: 'James is a 35-year-old investor based in Victoria with 2 investment properties and a PPOR. He earns $130k PAYG plus $75k from his partner, with $54k rental income. He has $180k usable equity, $85k cash, and $720k borrowing capacity. Properties are held in personal and joint names - he is interested in moving to trust structures. His goal is to scale to 5 properties within 3 years using equity recycling, targeting capital growth in VIC and QLD. He has a broker and accountant but no solicitor.',
      agentBriefs: {
        baselineBen: 'James is 35, based in VIC, with 2 investment properties plus a PPOR. He earns $130k PAYG (partner $75k), has $180k usable equity and $720k borrowing capacity. Goal is to scale from 2 to 5 properties in 3 years via equity recycling, focusing on capital growth. He has 3 years of investing experience but is unsure how to access equity without selling. He wants to explore trust structures for future purchases. Has a broker and accountant. Growth-oriented risk tolerance. 2 dependents.',
        finderFred: 'James is looking to buy his next property within 6 months, budget around $550k. He has $85k cash and $180k usable equity across his portfolio. Prefers VIC and QLD - specifically the Geelong corridor and south-east QLD. Open to interstate. Strategy is capital growth focused. Currently has a unit in Brunswick and a house in Geelong. Looking for his 3rd investment property on the path to 5 total. Has a broker. PAYG on $130k plus partner income of $75k.',
        investorCoach: 'James earns $130k/year PAYG, 6 years in role. Partner earns $75k and co-invests. PPOR worth $850k with $520k mortgage. Investment property 1: Brunswick unit, $620k value, $480k owing, $520/wk rent, personal name, bought 2021 for $545k. Investment property 2: Geelong house, $485k value, $390k owing, $410/wk rent, joint names, bought 2023 for $460k. Total equity ~$180k. Borrowing capacity $720k. $85k cash. $12k HECS, $18k car loan ($450/mo), $15k credit card limits. $6,500/mo expenses. 2 dependents. Goal: scale to 5 properties in 3 years via equity recycling, capital growth strategy.',
        dealSpecialist: 'James holds properties in personal name (Brunswick unit) and joint-personal name with partner (Geelong house). PPOR in joint names. No trusts or companies set up but actively interested in structuring future acquisitions through trusts. Marginal tax rate 37% ($130k + $54k rental). Has an accountant. No solicitor. No financial planner. No SMSF. 2 dependents. Partner co-invests. Looking at 3+ more purchases over 3 years so structure decisions are urgent.',
      },
      completenessScore: 92,
      dataGaps: ['hasFinancialPlanner', 'hasSolicitor'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'high-equity',
    label: 'Karen - High Equity',
    description: '4 properties, $620k equity, looking at development',
    profile: {
      personal: {
        firstName: 'Karen',
        email: 'karen.wright@example.com',
        phone: '0434 567 890',
        age: 45,
        state: 'QLD',
        dependents: 1,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 175000,
        employmentType: 'self-employed-company',
        yearsInRole: 12,
        hasHecsHelp: false,
        otherIncomeStreams: 'Share dividends, rental income from 4 properties',
        otherIncomeAmount: 95000,
      },
      financial: {
        cashSavings: 220000,
        monthlyExpenses: 7900,
        existingDebts: [],
        borrowingCapacity: 1200000,
        hasBroker: true,
        hasPreApproval: true,
        creditCardLimits: 30000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 1100000,
        homeMortgage: 280000,
        investmentProperties: [
          {
            location: 'Newstead, QLD',
            type: 'unit-apartment',
            currentValue: 580000,
            mortgageOwing: 320000,
            weeklyRent: 550,
            ownershipStructure: 'family-trust',
            yearPurchased: 2017,
            purchasePrice: 420000,
          },
          {
            location: 'Cannon Hill, QLD',
            type: 'house',
            currentValue: 780000,
            mortgageOwing: 450000,
            weeklyRent: 580,
            ownershipStructure: 'family-trust',
            yearPurchased: 2019,
            purchasePrice: 590000,
          },
          {
            location: 'Logan, QLD',
            type: 'duplex',
            currentValue: 620000,
            mortgageOwing: 400000,
            weeklyRent: 680,
            ownershipStructure: 'family-trust',
            yearPurchased: 2020,
            purchasePrice: 485000,
          },
          {
            location: 'Ipswich, QLD',
            type: 'house',
            currentValue: 450000,
            mortgageOwing: 340000,
            weeklyRent: 420,
            ownershipStructure: 'personal',
            yearPurchased: 2022,
            purchasePrice: 380000,
          },
        ],
        totalEquity: 620000,
      },
      goals: {
        primaryGoal: 'development',
        goalDetail: 'Explore subdivision and development opportunities to accelerate wealth',
        timeHorizon: '3-5-years',
        riskTolerance: 'aggressive',
        strategyPreference: 'value-add',
        nextStepTimeline: 'Next 3 months',
        budgetForNextPurchase: 800000,
      },
      locationPrefs: {
        preferredStates: ['QLD'],
        preferredRegions: ['Brisbane metro', 'Gold Coast corridor'],
        openToInterstate: false,
        proximityPreference: 'Metro only',
      },
      taxAndStructure: {
        marginalTaxRate: '45',
        hasAccountant: true,
        hasSolicitor: true,
        hasFinancialPlanner: true,
        existingStructures: ['family-trust', 'personal'],
        interestedInStructuring: false,
        hasSMSF: true,
        smsfBalance: 380000,
      },
      experience: {
        investingExperience: 'experienced',
        yearsInvesting: 8,
        biggestChallenge: 'Finding development-grade sites with the right zoning',
        specificQuestionsForToday: 'How to structure a subdivision JV',
      },
      summary: 'Karen is a 45-year-old experienced investor based in QLD, running her own company earning $175k plus $95k from investments. She has 4 investment properties plus a PPOR, with $620k usable equity and $1.2M borrowing capacity. Most properties held in a family trust, one in personal name. She has a full advisory team (accountant, solicitor, financial planner) and a $380k SMSF. Her focus is now on development and subdivision - she wants to find development sites in Brisbane metro within the next 3 months. Aggressive risk tolerance.',
      agentBriefs: {
        baselineBen: 'Karen is an experienced investor (8 years, 4 properties) based in QLD. Self-employed through her own company, earning $175k + $95k investment income. $620k equity, $1.2M borrowing capacity, $220k cash. She has moved past buy-and-hold and wants to pursue subdivision and development in Brisbane metro. Full advisory team in place. Family trust structures established. SMSF with $380k. 1 dependent. Her challenge is finding the right development sites with appropriate zoning. Aggressive risk tolerance, 3-5 year active strategy.',
        finderFred: 'Karen is looking for development-grade sites in Brisbane metro and Gold Coast corridor, budget up to $800k. She wants to move within 3 months - has pre-approval and $220k cash plus $620k equity. Not open to interstate. Metro locations only. She already owns in Newstead, Cannon Hill, Logan, and Ipswich. Strategy is value-add/development, specifically subdivision. She has 8 years experience and a broker. Self-employed on $175k.',
        investorCoach: 'Karen earns $175k self-employed (Pty Ltd), 12 years running. $95k additional income from shares and rent. PPOR worth $1.1M with $280k owing. Property 1: Newstead unit, $580k value, $320k owing, $550/wk rent, family trust, bought 2017. Property 2: Cannon Hill house, $780k value, $450k owing, $580/wk, family trust, bought 2019. Property 3: Logan duplex, $620k value, $400k owing, $680/wk, family trust, bought 2020. Property 4: Ipswich house, $450k value, $340k owing, $420/wk, personal name, bought 2022. Total equity $620k. Borrowing capacity $1.2M. $220k cash. $7,900/mo expenses. No debts outside mortgages. $30k credit card limits. Pre-approved. Goal: development and subdivision.',
        dealSpecialist: 'Karen has a family trust holding 3 of 4 investment properties (Newstead, Cannon Hill, Logan). Ipswich property in personal name. PPOR in personal name. Marginal tax rate 45% ($175k + $95k investment income). Full advisory team: accountant, solicitor, financial planner. SMSF with $380k balance. Not looking for new structures - existing trust setup works well. 1 dependent. Interested in structuring a subdivision JV. Self-employed through Pty Ltd, 12 years.',
      },
      completenessScore: 95,
      dataGaps: ['hecsBalance', 'partnerIncome'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'cash-flow-focused',
    label: 'Mike - Cash Flow Focused',
    description: '1 property, wants passive income',
    profile: {
      personal: {
        firstName: 'Mike',
        email: 'mike.donnelly@example.com',
        phone: '0445 678 901',
        age: 52,
        state: 'SA',
        dependents: 0,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 95000,
        employmentType: 'payg-fulltime',
        yearsInRole: 15,
        hasHecsHelp: false,
      },
      financial: {
        cashSavings: 60000,
        monthlyExpenses: 5200,
        existingDebts: [],
        borrowingCapacity: 520000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 8000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 550000,
        homeMortgage: 180000,
        investmentProperties: [
          {
            location: 'Elizabeth, SA',
            type: 'house',
            currentValue: 380000,
            mortgageOwing: 260000,
            weeklyRent: 370,
            ownershipStructure: 'personal',
            yearPurchased: 2020,
            purchasePrice: 295000,
          },
        ],
        totalEquity: 85000,
      },
      goals: {
        primaryGoal: 'passive-income',
        goalDetail: 'Build passive rental income to replace salary within 15 years',
        timeHorizon: '10-plus-years',
        riskTolerance: 'conservative',
        strategyPreference: 'cash-flow',
        nextStepTimeline: 'Next 12 months',
        budgetForNextPurchase: 400000,
      },
      locationPrefs: {
        preferredStates: ['SA', 'QLD'],
        openToInterstate: true,
        preferredRegions: ['Adelaide metro', 'Regional QLD'],
        proximityPreference: 'Happy with regional',
      },
      taxAndStructure: {
        marginalTaxRate: '32.5',
        hasAccountant: true,
        hasSolicitor: false,
        existingStructures: ['personal'],
        interestedInStructuring: false,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 4,
        biggestChallenge: 'Finding cash-flow-positive properties in the current market',
      },
      summary: 'Mike is a 52-year-old conservative investor based in South Australia, earning $95k PAYG. He has 1 investment property (Elizabeth, SA) plus a PPOR, with $85k usable equity and $520k borrowing capacity. His focus is building passive rental income to replace his salary within 15 years. He prefers cash-flow-positive properties and is open to SA and QLD including regional areas. Has a broker and accountant. $60k cash. No dependents, no partner co-investing.',
      agentBriefs: {
        baselineBen: 'Mike is 52, based in SA, conservative investor with a 15-year plan to replace his $95k salary with passive rental income. Has 1 investment property in Elizabeth SA plus a PPOR. $85k equity, $520k borrowing, $60k cash. 4 years experience. Cash-flow strategy. His challenge is finding properties that are actually cash-flow positive in the current market. Has a broker and accountant. No dependents, not investing with a partner. Needs a realistic roadmap to hit his income replacement goal.',
        finderFred: 'Mike is looking for his 2nd investment property within the next 12 months. Budget around $400k. Cash-flow strategy - must be cash-flow positive or very close to it. Open to SA (Adelaide metro) and QLD (regional). Happy with regional areas. Has $60k cash and $85k equity. Has a broker. Currently owns in Elizabeth, SA. PAYG on $95k, conservative risk tolerance. Prefers houses based on current portfolio.',
        investorCoach: 'Mike earns $95k/year PAYG, 15 years in role. No HECS, no other debts. PPOR worth $550k with $180k owing. Investment property: Elizabeth SA house, $380k value, $260k owing, $370/wk rent, personal name, bought 2020 for $295k. Total equity $85k. Borrowing capacity $520k. $60k cash. $5,200/mo expenses. $8k credit card limits. No dependents. Goal: build passive income stream to replace salary in 15 years. Conservative risk tolerance, cash-flow focused. Needs to model how many properties and what yield to hit his target.',
        dealSpecialist: 'Mike holds his investment property and PPOR in personal name. No trusts, companies, or SMSF. Not interested in restructuring at this stage. Marginal tax rate 32.5% ($95k income). Has an accountant. No solicitor or financial planner. No dependents, not investing with a partner. Conservative approach - asset protection is less of a concern given small portfolio. May need to revisit structures as portfolio grows.',
      },
      completenessScore: 82,
      dataGaps: ['age', 'otherIncomeStreams', 'hasFinancialPlanner', 'smsfBalance'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'asset-protection',
    label: 'Linda - Structure & Protection',
    description: '3 properties, needs trust/company structures',
    profile: {
      personal: {
        firstName: 'Linda',
        email: 'linda.park@example.com',
        phone: '0456 789 012',
        age: 41,
        state: 'NSW',
        dependents: 3,
        partnerInvesting: true,
        partnerIncome: 120000,
      },
      employment: {
        grossAnnualIncome: 210000,
        employmentType: 'payg-fulltime',
        yearsInRole: 8,
        hasHecsHelp: false,
        otherIncomeStreams: 'Rental income from 3 properties, partner income',
        otherIncomeAmount: 78000,
      },
      financial: {
        cashSavings: 150000,
        monthlyExpenses: 10000,
        existingDebts: [
          { type: 'car-loan', balance: 25000, monthlyRepayment: 600 },
        ],
        borrowingCapacity: 950000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 20000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 1400000,
        homeMortgage: 650000,
        investmentProperties: [
          {
            location: 'Parramatta, NSW',
            type: 'unit-apartment',
            currentValue: 650000,
            mortgageOwing: 480000,
            weeklyRent: 520,
            ownershipStructure: 'personal',
            yearPurchased: 2018,
            purchasePrice: 530000,
          },
          {
            location: 'Newcastle, NSW',
            type: 'house',
            currentValue: 720000,
            mortgageOwing: 520000,
            weeklyRent: 560,
            ownershipStructure: 'joint-personal',
            yearPurchased: 2020,
            purchasePrice: 580000,
          },
          {
            location: 'Wollongong, NSW',
            type: 'townhouse',
            currentValue: 580000,
            mortgageOwing: 430000,
            weeklyRent: 480,
            ownershipStructure: 'personal',
            yearPurchased: 2022,
            purchasePrice: 520000,
          },
        ],
        totalEquity: 450000,
      },
      goals: {
        primaryGoal: 'restructure',
        goalDetail: 'Restructure holdings into trusts and optimise tax position',
        timeHorizon: '5-10-years',
        riskTolerance: 'moderate',
        strategyPreference: 'balanced',
        nextStepTimeline: 'Next 3-6 months',
        budgetForNextPurchase: 700000,
      },
      locationPrefs: {
        preferredStates: ['NSW', 'QLD'],
        openToInterstate: true,
        preferredRegions: ['Sydney metro', 'Central Coast', 'South-east QLD'],
      },
      taxAndStructure: {
        marginalTaxRate: '45',
        hasAccountant: true,
        hasSolicitor: false,
        hasFinancialPlanner: false,
        existingStructures: ['personal', 'joint-personal'],
        interestedInStructuring: true,
        hasSMSF: false,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 6,
        biggestChallenge: 'Properties all in personal names, paying too much tax, worried about asset protection',
        specificQuestionsForToday: 'How to move existing properties into trust structures',
      },
      summary: 'Linda is a 41-year-old investor based in NSW earning $210k plus $120k from her partner. She has 3 investment properties plus a PPOR, all held in personal or joint-personal names. $450k equity, $950k borrowing capacity, $150k cash. Her primary concern is restructuring into trusts for asset protection and tax optimisation - she is on the 45% marginal rate and feels she is paying too much tax. Has an accountant but no solicitor or financial planner. 3 dependents. Partner co-invests. 6 years experience.',
      agentBriefs: {
        baselineBen: 'Linda is 41, based in NSW, earning $210k (partner $120k). 3 investment properties plus PPOR, all in personal/joint names. $450k equity, $950k borrowing, $150k cash. 6 years experience but still a novice in structures. Her top priority is restructuring into trusts for asset protection and tax optimisation - she is on the 45% rate and feels overexposed. Has a broker and accountant but no solicitor. 3 dependents. Moderate risk tolerance, balanced strategy. Wants to continue growing the portfolio while fixing the structural issues.',
        finderFred: 'Linda is looking to buy her 4th investment property within 3-6 months, budget around $700k. Prefers NSW (Sydney metro, Central Coast) and south-east QLD. Open to interstate. Has $150k cash and $450k equity. Balanced strategy - mix of growth and cash flow. Currently owns in Parramatta, Newcastle, and Wollongong. Has a broker. PAYG on $210k plus partner $120k. Moderate risk tolerance. Note: she is in the process of restructuring so new purchases may need to go into a trust.',
        investorCoach: 'Linda earns $210k/year PAYG, 8 years in role. Partner earns $120k and co-invests. PPOR worth $1.4M with $650k owing. Property 1: Parramatta unit, $650k value, $480k owing, $520/wk rent, personal name, bought 2018 for $530k. Property 2: Newcastle house, $720k value, $520k owing, $560/wk, joint names, bought 2020 for $580k. Property 3: Wollongong townhouse, $580k value, $430k owing, $480/wk, personal name, bought 2022 for $520k. Total equity $450k. Borrowing capacity $950k. $150k cash. $25k car loan ($600/mo). $10k/mo expenses. $20k credit card limits. 3 dependents. Goal: restructure for tax and protection while continuing to grow. Balanced strategy.',
        dealSpecialist: 'Linda holds all properties in personal or joint-personal names - no trusts, companies, or SMSF. This is her primary pain point. She wants to restructure into trust structures for asset protection and tax optimisation. Marginal tax rate 45% ($210k + $78k rental income). Has an accountant but NO solicitor or financial planner - will need both for restructuring. 3 dependents. Partner co-invests ($120k income). Key question: how to move existing properties into trusts (stamp duty implications, CGT triggers). Portfolio: Parramatta (personal), Newcastle (joint), Wollongong (personal). 6 years investing experience.',
      },
      completenessScore: 88,
      dataGaps: ['proximityPreference', 'smsfBalance', 'yearsInvesting'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'fifo-contractor',
    label: 'Tom - FIFO Contractor',
    description: 'High income, PPOR only, wants first investment',
    profile: {
      personal: {
        firstName: 'Tom',
        email: 'tom.harris@example.com',
        phone: '0467 890 123',
        age: 31,
        state: 'WA',
        dependents: 0,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 185000,
        employmentType: 'contractor',
        yearsInRole: 4,
        hasHecsHelp: false,
        otherIncomeStreams: 'Occasional overtime and shutdown work',
        otherIncomeAmount: 25000,
      },
      financial: {
        cashSavings: 120000,
        monthlyExpenses: 4800,
        existingDebts: [
          { type: 'car-loan', balance: 35000, monthlyRepayment: 750 },
        ],
        borrowingCapacity: 680000,
        hasBroker: false,
        hasPreApproval: false,
        creditCardLimits: 12000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 620000,
        homeMortgage: 380000,
        investmentProperties: [],
        totalEquity: 240000,
      },
      goals: {
        primaryGoal: 'first-property',
        goalDetail: 'Buy first investment property using PPOR equity, build portfolio quickly while income is high',
        timeHorizon: '5-10-years',
        riskTolerance: 'aggressive',
        strategyPreference: 'capital-growth',
        nextStepTimeline: 'Next 3-6 months',
        budgetForNextPurchase: 550000,
      },
      locationPrefs: {
        preferredStates: ['WA', 'QLD'],
        preferredRegions: ['Perth metro', 'South-east QLD'],
        openToInterstate: true,
        proximityPreference: 'Metro - needs to be easy to manage remotely while on site',
      },
      taxAndStructure: {
        marginalTaxRate: '45',
        hasAccountant: true,
        hasSolicitor: false,
        existingStructures: [],
        interestedInStructuring: true,
      },
      experience: {
        investingExperience: 'owner-occupier',
        yearsInvesting: 0,
        biggestChallenge: 'Not sure if lenders will accept contractor income, and how to manage properties while FIFO',
        specificQuestionsForToday: 'Can I use my PPOR equity for a deposit? Do I need 2 years of BAS as a contractor?',
      },
      summary: 'Tom is a 31-year-old FIFO contractor based in WA, earning $185k plus ~$25k overtime. He owns a PPOR in Perth worth $620k with $380k owing, giving him ~$240k equity. No investment properties yet. $120k cash savings, $680k borrowing capacity. He has a $35k car loan. His challenge is understanding contractor lending requirements (BAS history, contract length) and managing property remotely while working FIFO rosters. Aggressive risk tolerance, wants to build quickly while his income is high. Has an accountant but no broker or solicitor.',
      agentBriefs: {
        baselineBen: 'Tom is 31, based in WA, working FIFO as a contractor on $185k + $25k overtime. Owns a PPOR in Perth ($620k value, $380k owing) but no investment properties. $120k cash, $240k equity, $680k borrowing capacity. Aggressive risk tolerance - wants to build a portfolio quickly while his mining income is high. Main concerns: whether lenders will accept contractor income without 2 years of BAS, and how to manage properties remotely on FIFO rosters. Has an accountant. Interested in structures from the start. No dependents.',
        finderFred: 'Tom wants his first investment property within 3-6 months, budget $550k. $120k cash and $240k PPOR equity available. Prefers Perth metro or south-east QLD - must be easy to manage remotely (FIFO worker, away 2 weeks on/1 week off). Open to interstate. Capital growth strategy. No existing investments. Has no broker yet. Contractor on $185k. Aggressive risk tolerance. Needs low-maintenance property - no renovation projects.',
        investorCoach: 'Tom earns $185k/year as a contractor (FIFO mining), 4 years on current contract. $25k additional overtime/shutdown income. No HECS. PPOR worth $620k with $380k owing. No investment properties. $120k cash. $4,800/mo expenses. $35k car loan ($750/mo). $12k credit cards. Borrowing capacity $680k. No broker, no pre-approval. Key lending question: contractor with 4 years history but needs to confirm lender acceptance of contract income. Goal: first IP using PPOR equity, then build quickly. Aggressive risk, capital growth, 5-10 year horizon.',
        dealSpecialist: 'Tom has no ownership structures - PPOR in personal name, no trusts, companies, or SMSF. On the 45% marginal tax rate ($185k + $25k overtime). Has an accountant. No solicitor or financial planner. Interested in setting up structures from the start before buying first IP. No dependents, not investing with a partner. Contractor status may affect lending but not structures. Worth discussing trust vs personal name for first purchase given his tax rate and growth plans.',
      },
      completenessScore: 85,
      dataGaps: ['hasBroker', 'hasFinancialPlanner', 'monthlyExpenses'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'govt-couple',
    label: 'Priya & Raj - Government Couple',
    description: 'Dual income, 1 property, ACT-based, steady growth plan',
    profile: {
      personal: {
        firstName: 'Priya',
        email: 'priya.sharma@example.com',
        phone: '0478 901 234',
        age: 38,
        state: 'ACT',
        dependents: 2,
        partnerInvesting: true,
        partnerIncome: 105000,
      },
      employment: {
        grossAnnualIncome: 115000,
        employmentType: 'payg-fulltime',
        yearsInRole: 10,
        hasHecsHelp: true,
        hecsBalance: 18000,
        otherIncomeStreams: 'Rental income from 1 investment property',
        otherIncomeAmount: 26000,
      },
      financial: {
        cashSavings: 95000,
        monthlyExpenses: 7200,
        existingDebts: [
          { type: 'hecs', balance: 18000 },
          { type: 'personal-loan', balance: 8000, monthlyRepayment: 300 },
        ],
        borrowingCapacity: 850000,
        hasBroker: true,
        hasPreApproval: true,
        creditCardLimits: 10000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 980000,
        homeMortgage: 520000,
        investmentProperties: [
          {
            location: 'Gungahlin, ACT',
            type: 'townhouse',
            currentValue: 680000,
            mortgageOwing: 510000,
            weeklyRent: 550,
            ownershipStructure: 'joint-personal',
            yearPurchased: 2022,
            purchasePrice: 620000,
          },
        ],
        totalEquity: 150000,
      },
      goals: {
        primaryGoal: 'grow-portfolio',
        goalDetail: 'Build to 4 properties over the next 5 years for long-term wealth and eventual passive income',
        timeHorizon: '5-10-years',
        riskTolerance: 'moderate',
        strategyPreference: 'balanced',
        nextStepTimeline: 'Next 6-12 months',
        budgetForNextPurchase: 600000,
      },
      locationPrefs: {
        preferredStates: ['ACT', 'NSW', 'QLD'],
        preferredRegions: ['Canberra surrounds', 'South Coast NSW', 'South-east QLD'],
        openToInterstate: true,
        proximityPreference: 'Metro and major regional',
      },
      taxAndStructure: {
        marginalTaxRate: '37',
        hasAccountant: true,
        hasSolicitor: false,
        hasFinancialPlanner: false,
        existingStructures: ['joint-personal'],
        interestedInStructuring: true,
        hasSMSF: false,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 2,
        biggestChallenge: 'ACT market feels overpriced - not sure whether to keep buying locally or go interstate',
        specificQuestionsForToday: 'Should we buy the next one in a trust given we both have government jobs?',
      },
      summary: 'Priya (38) and Raj are a dual-income government couple based in the ACT, earning $115k and $105k respectively. They own a PPOR in Canberra ($980k, $520k owing) and 1 investment townhouse in Gungahlin ($680k, $510k owing, $550/wk rent, joint names). $150k equity, $850k borrowing, $95k cash. Pre-approved. 2 dependents. Their goal is to build to 4 properties over 5 years using a balanced growth and cash-flow strategy. They are considering whether to keep buying in the ACT or go interstate, and want to explore trust structures for future purchases given both work in government.',
      agentBriefs: {
        baselineBen: 'Priya and Raj are a government couple in the ACT, combined income $220k ($115k + $105k). Own a PPOR and 1 investment townhouse in Gungahlin (joint names). $150k equity, $850k borrowing, $95k cash. Pre-approved. 2 dependents, 2 years investing experience. Goal: 4 properties in 5 years, balanced strategy. Their challenge is whether ACT is too expensive and whether to go interstate for better value. Interested in trust structures for future purchases given government employment. Have a broker and accountant. Moderate risk tolerance.',
        finderFred: 'Priya and Raj want their 2nd investment property within 6-12 months. Budget $600k. $95k cash, $150k equity. Pre-approved. Balanced strategy - want a mix of growth and yield. Currently own a Gungahlin townhouse. Open to ACT, south coast NSW, and south-east QLD. Open to interstate. Metro and major regional. Combined PAYG $220k. Moderate risk. Have a broker. Key question: whether to stay in ACT at higher prices or buy better value interstate.',
        investorCoach: 'Priya earns $115k PAYG (government, 10 years). Raj earns $105k PAYG (government). Both co-invest. PPOR worth $980k with $520k owing. Investment: Gungahlin townhouse, $680k value, $510k owing, $550/wk rent, joint names, bought 2022 for $620k. Total equity ~$150k. Borrowing capacity $850k. $95k cash. $18k HECS (Priya), $8k personal loan ($300/mo). $10k credit cards. $7,200/mo expenses. 2 dependents. Pre-approved. Goal: 4 properties in 5 years, balanced strategy. Secure employment, steady serviceability.',
        dealSpecialist: 'Priya and Raj hold their investment property and PPOR in joint-personal names. No trusts or companies. $18k HECS on Priya. Combined marginal rate: Priya 37% ($115k + $26k rental share), Raj 37% ($105k). Both are government employees so stable income but potentially exposed professionally. Interested in trust structures for next purchase. Have an accountant. No solicitor or financial planner. 2 dependents. Need to weigh whether joint-personal or trust is better for their next acquisition.',
      },
      completenessScore: 90,
      dataGaps: ['hasSolicitor', 'hasFinancialPlanner', 'proximityPreference'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'smsf-retiree',
    label: 'Dave - Early Retiree with SMSF',
    description: '5 properties, SMSF, optimising for retirement income',
    profile: {
      personal: {
        firstName: 'Dave',
        email: 'dave.thompson@example.com',
        phone: '0489 012 345',
        age: 58,
        state: 'TAS',
        dependents: 0,
        partnerInvesting: true,
        partnerIncome: 0,
      },
      employment: {
        grossAnnualIncome: 0,
        employmentType: 'self-employed-company',
        yearsInRole: 0,
        hasHecsHelp: false,
        otherIncomeStreams: 'Rental income from 5 properties, SMSF pension, share dividends',
        otherIncomeAmount: 142000,
      },
      financial: {
        cashSavings: 180000,
        monthlyExpenses: 6500,
        existingDebts: [],
        borrowingCapacity: 0,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 15000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 850000,
        homeMortgage: 0,
        investmentProperties: [
          {
            location: 'Hobart, TAS',
            type: 'house',
            currentValue: 620000,
            mortgageOwing: 0,
            weeklyRent: 520,
            ownershipStructure: 'family-trust',
            yearPurchased: 2010,
            purchasePrice: 280000,
          },
          {
            location: 'Launceston, TAS',
            type: 'duplex',
            currentValue: 480000,
            mortgageOwing: 0,
            weeklyRent: 620,
            ownershipStructure: 'family-trust',
            yearPurchased: 2013,
            purchasePrice: 240000,
          },
          {
            location: 'Devonport, TAS',
            type: 'house',
            currentValue: 380000,
            mortgageOwing: 120000,
            weeklyRent: 380,
            ownershipStructure: 'personal',
            yearPurchased: 2018,
            purchasePrice: 265000,
          },
          {
            location: 'Geelong, VIC',
            type: 'townhouse',
            currentValue: 520000,
            mortgageOwing: 180000,
            weeklyRent: 430,
            ownershipStructure: 'smsf',
            yearPurchased: 2019,
            purchasePrice: 410000,
          },
          {
            location: 'Burnie, TAS',
            type: 'house',
            currentValue: 340000,
            mortgageOwing: 0,
            weeklyRent: 350,
            ownershipStructure: 'family-trust',
            yearPurchased: 2015,
            purchasePrice: 195000,
          },
        ],
        totalEquity: 2040000,
      },
      goals: {
        primaryGoal: 'retirement',
        goalDetail: 'Maximise passive rental income and simplify portfolio for retirement, considering selling 1-2 underperformers',
        timeHorizon: '1-3-years',
        riskTolerance: 'conservative',
        strategyPreference: 'cash-flow',
        nextStepTimeline: 'Reviewing portfolio now',
      },
      locationPrefs: {
        preferredStates: ['TAS'],
        openToInterstate: false,
        preferredRegions: ['Hobart', 'Launceston'],
        proximityPreference: 'Prefer properties I can drive to',
      },
      taxAndStructure: {
        marginalTaxRate: '37',
        hasAccountant: true,
        hasSolicitor: true,
        hasFinancialPlanner: true,
        existingStructures: ['family-trust', 'personal', 'smsf'],
        interestedInStructuring: false,
        hasSMSF: true,
        smsfBalance: 620000,
      },
      experience: {
        investingExperience: 'advanced',
        yearsInvesting: 16,
        biggestChallenge: 'Working out which properties to keep and which to sell for a simpler retirement',
        specificQuestionsForToday: 'Should I sell the Devonport and Burnie properties and consolidate into fewer higher-quality assets?',
      },
      summary: 'Dave is a 58-year-old early retiree based in Tasmania with 5 investment properties and a PPOR. No employment income - lives off $142k/year from rental income, SMSF pension, and share dividends. $2M+ total equity across the portfolio, $180k cash. Properties mostly unencumbered (only $300k total owing). Mix of family trust, personal, and SMSF ownership. Full advisory team. His goal is to simplify the portfolio for retirement - considering selling underperforming regionals and consolidating. Conservative risk, cash-flow focus. SMSF balance $620k with one property inside it.',
      agentBriefs: {
        baselineBen: 'Dave is 58, early retiree in TAS. 16 years investing, 5 properties plus PPOR. No employment income - $142k/year from rent, SMSF pension, and dividends. $2M+ equity, most properties are unencumbered. Mix of family trust, personal name, and SMSF structures. Full advisory team. Conservative, cash-flow focused. His challenge now is simplifying: he wants to work out which properties to keep and which to sell. Considering selling lower-yield regionals (Devonport, Burnie) and consolidating. Partner is retired too. No dependents. Not looking to buy more - optimising what he has.',
        finderFred: 'Dave is NOT looking to buy - he is in sell/consolidate mode. If anything, he may want help valuing what to sell vs keep. 5 properties across TAS and VIC. Not open to interstate purchases. Prefers properties within driving distance of Hobart. Cash-flow focus, conservative. If he sells 2 underperformers he may reinvest proceeds into 1 higher-quality asset in Hobart or Launceston, budget would be $500k-$700k.',
        investorCoach: 'Dave has no employment income - retired early. Lives off portfolio: Hobart house ($620k, no mortgage, $520/wk, trust). Launceston duplex ($480k, no mortgage, $620/wk, trust). Devonport house ($380k, $120k owing, $380/wk, personal). Geelong townhouse ($520k, $180k owing, $430/wk, SMSF). Burnie house ($340k, no mortgage, $350/wk, trust). PPOR $850k, no mortgage. Total equity ~$2M. $180k cash. $6,500/mo expenses. No debts outside property. SMSF $620k (includes Geelong property). $142k/year passive income. Question: which properties are underperforming on yield vs capital vs hassle, and what does the portfolio look like after selling 1-2?',
        dealSpecialist: 'Dave has a well-established structure: family trust (3 properties), personal name (1), SMSF (1). Full advisory team: accountant, solicitor, financial planner. SMSF balance $620k with Geelong townhouse inside it ($180k loan within SMSF - check LRBA compliance as he approaches pension phase). Marginal tax rate 37% on $142k passive income. Not interested in new structures. Key questions: CGT implications of selling trust-held vs personally-held properties, and SMSF transition from accumulation to pension phase with property inside it. No dependents. Partner involved (retired).',
      },
      completenessScore: 96,
      dataGaps: ['partnerIncome', 'creditCardLimits'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'tradie-builder',
    label: 'Anh - Self-Employed Tradie',
    description: 'Sole trader electrician, 2 properties, growth focus',
    profile: {
      personal: {
        firstName: 'Anh',
        email: 'anh.nguyen@example.com',
        phone: '0490 123 456',
        age: 33,
        state: 'NSW',
        dependents: 1,
        partnerInvesting: true,
        partnerIncome: 68000,
      },
      employment: {
        grossAnnualIncome: 140000,
        employmentType: 'self-employed-sole',
        yearsInRole: 6,
        hasHecsHelp: false,
        otherIncomeStreams: 'Rental income from 2 properties, occasional cash jobs',
        otherIncomeAmount: 48000,
      },
      financial: {
        cashSavings: 75000,
        monthlyExpenses: 5800,
        existingDebts: [
          { type: 'car-loan', balance: 28000, monthlyRepayment: 600 },
          { type: 'other', balance: 15000, monthlyRepayment: 400 },
        ],
        borrowingCapacity: 620000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 8000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 780000,
        homeMortgage: 450000,
        investmentProperties: [
          {
            location: 'Penrith, NSW',
            type: 'house',
            currentValue: 720000,
            mortgageOwing: 520000,
            weeklyRent: 550,
            ownershipStructure: 'personal',
            yearPurchased: 2021,
            purchasePrice: 610000,
          },
          {
            location: 'Campbelltown, NSW',
            type: 'house',
            currentValue: 680000,
            mortgageOwing: 510000,
            weeklyRent: 520,
            ownershipStructure: 'personal',
            yearPurchased: 2023,
            purchasePrice: 640000,
          },
        ],
        totalEquity: 130000,
      },
      goals: {
        primaryGoal: 'grow-portfolio',
        goalDetail: 'Get to 5 properties in the next 5 years, use trade skills for cosmetic renos to add value',
        timeHorizon: '5-10-years',
        riskTolerance: 'growth',
        strategyPreference: 'value-add',
        nextStepTimeline: 'Next 6-12 months',
        budgetForNextPurchase: 500000,
      },
      locationPrefs: {
        preferredStates: ['NSW'],
        preferredRegions: ['Western Sydney', 'Central Coast', 'Hunter Valley'],
        openToInterstate: false,
        proximityPreference: 'Needs to be within 1-2 hours of Penrith so I can do the reno work myself',
      },
      taxAndStructure: {
        marginalTaxRate: '37',
        hasAccountant: true,
        hasSolicitor: false,
        existingStructures: ['personal'],
        interestedInStructuring: true,
        hasSMSF: false,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 3,
        biggestChallenge: 'Lenders keep wanting 2 years of tax returns and my accountant minimises my income - borrowing capacity is lower than it should be',
        specificQuestionsForToday: 'How do I get around the self-employed lending problem when my taxable income is low but my actual income is higher?',
      },
      summary: 'Anh is a 33-year-old self-employed electrician (sole trader) based in western Sydney, earning ~$140k plus $48k from rent and side work. He has 2 investment houses in Penrith and Campbelltown (both in personal name) plus a PPOR. $130k equity, $620k borrowing capacity, $75k cash. His key advantage is trade skills for value-add renovations. His key problem is self-employed lending - his accountant minimises taxable income which kills borrowing capacity. Has a broker and accountant. 1 dependent, partner earns $68k. Interested in trust structures. Growth/value-add strategy.',
      agentBriefs: {
        baselineBen: 'Anh is 33, self-employed electrician (sole trader) in western Sydney. $140k income + $48k from rent/side work. Owns PPOR and 2 investment houses (Penrith, Campbelltown, both personal name). $130k equity, $620k borrowing, $75k cash. Partner earns $68k, 1 dependent. 3 years investing experience. Strategy: value-add using his trade skills for cosmetic renos. Biggest challenge: self-employed lending gap - accountant minimises income, lenders see lower borrowing capacity than his actual income supports. Interested in trust structures. Growth risk tolerance. Wants 5 properties in 5 years.',
        finderFred: 'Anh wants his 3rd investment within 6-12 months. Budget $500k. Strategy is value-add - he is an electrician and can do cosmetic renovations himself, so properties with reno upside are ideal. Must be within 1-2 hours of Penrith so he can physically do the work. Prefers western Sydney, Central Coast, and Hunter Valley. NOT open to interstate. $75k cash, $130k equity. Has a broker. Self-employed sole trader on $140k + partner $68k. Growth risk tolerance.',
        investorCoach: 'Anh earns $140k/year as self-employed electrician (sole trader), 6 years. Partner earns $68k PAYG. PPOR worth $780k, $450k owing. Investment 1: Penrith house, $720k value, $520k owing, $550/wk rent, personal name, bought 2021 for $610k. Investment 2: Campbelltown house, $680k value, $510k owing, $520/wk rent, personal name, bought 2023 for $640k. $130k equity, $620k borrowing. $75k cash. $28k car loan ($600/mo), $15k tool/equipment finance ($400/mo). $5,800/mo expenses. $8k credit cards. 1 dependent. Key issue: self-employed lending - accountant minimises taxable income so lenders see lower serviceability. Needs strategy to bridge the gap (add-backs, different lender, partner as primary borrower).',
        dealSpecialist: 'Anh holds everything in personal name - both investment properties and PPOR. Sole trader electrician, no company structure. Marginal tax rate 37% ($140k + $48k other). Has an accountant (who minimises tax aggressively) and a broker. No solicitor. No SMSF. Interested in trust structures for future purchases. 1 dependent, partner co-invests ($68k). Key structural question: whether to set up a trust for next purchase, and whether the tax minimisation strategy from his accountant is actually costing him in borrowing capacity - may need to balance tax efficiency vs lending.',
      },
      completenessScore: 86,
      dataGaps: ['hasFinancialPlanner', 'hasSolicitor', 'hecsBalance'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'single-mum-restart',
    label: 'Rachel - Divorced, Rebuilding',
    description: 'Recently divorced, PPOR equity, 1 IP from settlement',
    profile: {
      personal: {
        firstName: 'Rachel',
        email: 'rachel.kelly@example.com',
        phone: '0401 234 567',
        age: 44,
        state: 'WA',
        dependents: 2,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 98000,
        employmentType: 'payg-fulltime',
        yearsInRole: 5,
        hasHecsHelp: true,
        hecsBalance: 22000,
        otherIncomeStreams: 'Rental income from 1 investment property',
        otherIncomeAmount: 24000,
      },
      financial: {
        cashSavings: 40000,
        monthlyExpenses: 6800,
        existingDebts: [
          { type: 'hecs', balance: 22000 },
          { type: 'credit-card', balance: 6000, monthlyRepayment: 250 },
        ],
        borrowingCapacity: 420000,
        hasBroker: false,
        hasPreApproval: false,
        creditCardLimits: 12000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 720000,
        homeMortgage: 340000,
        investmentProperties: [
          {
            location: 'Baldivis, WA',
            type: 'house',
            currentValue: 520000,
            mortgageOwing: 350000,
            weeklyRent: 470,
            ownershipStructure: 'personal',
            yearPurchased: 2019,
            purchasePrice: 410000,
          },
        ],
        totalEquity: 200000,
      },
      goals: {
        primaryGoal: 'passive-income',
        goalDetail: 'Build financial security for myself and my kids after divorce - want rental income as safety net',
        timeHorizon: '10-plus-years',
        riskTolerance: 'conservative',
        strategyPreference: 'cash-flow',
        nextStepTimeline: 'Next 12-18 months, once I feel more settled',
        budgetForNextPurchase: 420000,
      },
      locationPrefs: {
        preferredStates: ['WA'],
        openToInterstate: false,
        preferredRegions: ['Perth south metro', 'Mandurah'],
        proximityPreference: 'Close to home - want to be able to drive past',
      },
      taxAndStructure: {
        marginalTaxRate: '32.5',
        hasAccountant: true,
        hasSolicitor: true,
        hasFinancialPlanner: false,
        existingStructures: ['personal'],
        interestedInStructuring: false,
      },
      experience: {
        investingExperience: 'some-knowledge',
        yearsInvesting: 0,
        biggestChallenge: 'The investment property was part of my divorce settlement so I have never actually bought or managed one before - feeling overwhelmed',
        specificQuestionsForToday: 'Should I keep the Baldivis property or sell it and invest the equity differently?',
      },
      summary: 'Rachel is a 44-year-old single mum of 2 based in WA, earning $98k PAYG. She recently went through a divorce and received a PPOR ($720k, $340k owing) and 1 investment house in Baldivis ($520k, $350k owing, $470/wk rent) as part of her settlement. $200k equity, $420k borrowing, $40k cash. She has never actually managed an investment property before - the Baldivis house came from the settlement. Her priority is financial security for her and her kids, not aggressive growth. Conservative, cash-flow focused, 10+ year horizon. Has an accountant and solicitor from the divorce. No broker or financial planner.',
      agentBriefs: {
        baselineBen: 'Rachel is 44, recently divorced single mum of 2 in WA. Earns $98k PAYG. Received PPOR and 1 investment property (Baldivis house) through divorce settlement. $200k equity, $420k borrowing, $40k cash. She has never actually bought or managed a property herself - the Baldivis IP was her ex-husband\'s deal. Feeling overwhelmed but motivated to build financial independence. Conservative risk tolerance, cash-flow focused. Not in a rush - wants to learn and get comfortable before making moves. Has an accountant and solicitor from the divorce. No broker. 2 dependents.',
        finderFred: 'Rachel is not ready to buy immediately - timeline is 12-18 months. Budget around $420k when she is ready. Cash-flow is the priority - she needs rental income as a safety net, not speculative growth. Prefers WA only, Perth south metro and Mandurah. Close to home. Not open to interstate. $40k cash, $200k equity. Has no broker. $98k PAYG. Conservative. First question to answer: whether to keep the Baldivis house or sell it. If she keeps it, she will eventually look for a 2nd IP.',
        investorCoach: 'Rachel earns $98k PAYG, 5 years in role. 2 dependents, no partner. PPOR worth $720k with $340k owing. Investment: Baldivis house, $520k value, $350k owing, $470/wk rent, personal name (received in 2019 divorce settlement, originally bought at $410k). $200k equity. Borrowing capacity $420k. $40k cash. $22k HECS. $6k credit card debt ($250/mo). $12k credit card limits. $6,800/mo expenses (higher due to single-parent household). First question: is the Baldivis property performing well enough to keep? What is the yield, cash flow after expenses, and growth outlook? She needs a clear picture before deciding to hold or sell.',
        dealSpecialist: 'Rachel holds everything in personal name. No trusts, companies, or SMSF. Not interested in structures at this stage. Marginal tax rate 32.5% ($98k + $24k rent). Has an accountant and solicitor (both from divorce proceedings). No financial planner. 2 dependents. Single income. The Baldivis property was transferred as part of divorce settlement - need to confirm the CGT cost base was correctly established at transfer. Conservative approach, not looking for complex structures. Protection concern is minimal given moderate portfolio.',
      },
      completenessScore: 82,
      dataGaps: ['hasFinancialPlanner', 'hasBroker', 'smsfBalance', 'monthlyExpenses'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'young-professional',
    label: 'Liam - High-Income Renter',
    description: 'No PPOR, renting, wants to rentvest',
    profile: {
      personal: {
        firstName: 'Liam',
        email: 'liam.obrien@example.com',
        phone: '0412 098 765',
        age: 27,
        state: 'VIC',
        dependents: 0,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 155000,
        employmentType: 'payg-fulltime',
        yearsInRole: 3,
        hasHecsHelp: true,
        hecsBalance: 42000,
      },
      financial: {
        cashSavings: 85000,
        monthlyExpenses: 4200,
        existingDebts: [
          { type: 'hecs', balance: 42000 },
        ],
        borrowingCapacity: 750000,
        hasBroker: false,
        hasPreApproval: false,
        creditCardLimits: 10000,
      },
      portfolio: {
        ownsHome: false,
        investmentProperties: [],
        totalEquity: 0,
      },
      goals: {
        primaryGoal: 'first-property',
        goalDetail: 'Rentvest strategy - keep renting in Melbourne CBD, buy investment property interstate where the numbers work',
        timeHorizon: '10-plus-years',
        riskTolerance: 'growth',
        strategyPreference: 'capital-growth',
        nextStepTimeline: 'Next 3-6 months',
        budgetForNextPurchase: 550000,
      },
      locationPrefs: {
        preferredStates: ['QLD', 'SA', 'WA'],
        preferredRegions: ['Brisbane metro', 'Adelaide metro', 'Perth metro'],
        openToInterstate: true,
        proximityPreference: 'Happy to buy interstate - will use a property manager',
      },
      taxAndStructure: {
        marginalTaxRate: '37',
        hasAccountant: false,
        hasSolicitor: false,
        existingStructures: [],
        interestedInStructuring: true,
      },
      experience: {
        investingExperience: 'some-knowledge',
        yearsInvesting: 0,
        biggestChallenge: 'Cannot afford to buy a PPOR in Melbourne - friends say I should buy where I live but the numbers do not make sense',
        specificQuestionsForToday: 'Is rentvestin actually a good strategy or will I regret not having a PPOR for the CGT exemption?',
      },
      summary: 'Liam is a 27-year-old tech professional in Melbourne earning $155k PAYG. He rents in the CBD and has no property at all. $85k savings, $750k borrowing capacity, $42k HECS. He wants to rentvest - continue renting in Melbourne while buying an investment property interstate where yields and growth make more sense. Looking at Brisbane, Adelaide, or Perth metro. Growth strategy, 10+ year horizon. No broker, no accountant, no structures. Interested in setting things up right from the start. His concern is whether rentvestin is the right move vs stretching to buy a PPOR.',
      agentBriefs: {
        baselineBen: 'Liam is 27, renting in Melbourne CBD, earning $155k PAYG in tech. No property at all. $85k cash, $750k borrowing, $42k HECS. Wants to rentvest - buy interstate investment while continuing to rent in Melbourne because PPOR maths do not work here. Growth strategy, 10+ year horizon. No broker, accountant, or existing structures. Interested in setting up correctly from the start. His friends think he should buy a PPOR first - he wants validation or challenge on the rentvesting approach. No dependents, not investing with a partner.',
        finderFred: 'Liam wants his first investment property within 3-6 months. Budget up to $550k. Rentvesting - he lives in Melbourne CBD (renting) and wants to buy interstate. Looking at Brisbane metro, Adelaide metro, or Perth metro. Open to all three. Capital growth strategy. Will use a property manager. No existing portfolio. $85k cash for deposit. No broker. PAYG $155k. Growth risk tolerance. Needs guidance on which market to enter.',
        investorCoach: 'Liam earns $155k PAYG, 3 years in role (tech). Renting in Melbourne CBD. No property at all - no PPOR, no investments. $85k cash savings. $4,200/mo expenses (rent ~$2,400 of that). $42k HECS. No other debts. $10k credit cards. Borrowing capacity $750k. No broker, no pre-approval. Strategy: rentvest to get into market without Melbourne PPOR prices. Key analysis: compare renting + investing vs buying PPOR - what does the 10-year outcome look like for each scenario? Need to factor in CGT exemption loss, rental deductions, and growth assumptions.',
        dealSpecialist: 'Liam has no existing structures - clean slate. No trusts, companies, SMSF. On the 37% marginal tax rate ($155k). No accountant or solicitor. Interested in getting structures right from the first purchase. No dependents, no partner. Key question: should first purchase be in personal name or trust? As a rentvester he will not get PPOR CGT exemption anyway, so trust may make sense from day one. Also needs to engage an accountant and consider depreciation benefits on new/near-new stock.',
      },
      completenessScore: 80,
      dataGaps: ['hasBroker', 'hasAccountant', 'hasFinancialPlanner', 'monthlyExpenses', 'age'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
];
