import type { ClientProfile } from './stores/financial-store';

export interface TestProfile {
  id: string;
  label: string;
  description: string;
  profile: ClientProfile;
}

export const TEST_PROFILES: TestProfile[] = [
  {
    id: 'first-timer',
    label: 'Sarah - First Timer',
    description: 'No properties, starting from scratch',
    profile: {
      personal: {
        firstName: 'Sarah',
        age: 28,
        state: 'VIC',
        dependents: 0,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 85000,
        employmentType: 'payg-fulltime',
        yearsInRole: 3,
        hasHecsHelp: true,
        hecsBalance: 28000,
      },
      financial: {
        cashSavings: 45000,
        monthlyExpenses: 4600,
        existingDebts: [
          { type: 'hecs', balance: 28000 },
        ],
        borrowingCapacity: 450000,
        hasBroker: false,
        hasPreApproval: false,
        creditCardLimits: 5000,
      },
      portfolio: {
        ownsHome: false,
        investmentProperties: [],
        totalEquity: 0,
      },
      goals: {
        primaryGoal: 'first-property',
        goalDetail: 'Buy first investment property within 12 months',
        timeHorizon: '10-plus-years',
        riskTolerance: 'moderate',
        strategyPreference: 'unsure',
        nextStepTimeline: 'Next 6-12 months',
        budgetForNextPurchase: 450000,
      },
      locationPrefs: {
        preferredStates: ['VIC'],
        openToInterstate: true,
        proximityPreference: 'Metro and major regional',
      },
      taxAndStructure: {
        marginalTaxRate: '32.5',
        hasAccountant: false,
        hasSolicitor: false,
        existingStructures: [],
      },
      experience: {
        investingExperience: 'some-knowledge',
        biggestChallenge: 'Not sure where to start or what type of property to look for',
      },
      summary: 'Sarah is a 28-year-old first-time investor based in Victoria, earning $85k/year as a PAYG employee. She has $45k in savings but no existing properties or equity. Her borrowing capacity is around $450k. She has a $28k HECS debt. She wants to buy her first investment property within the next 12 months and is open to interstate purchases. She has a moderate risk tolerance and a long-term horizon of 10+ years but is unsure whether to focus on growth or cash flow.',
      agentBriefs: {
        baselineBen: 'Sarah is a first-time investor based in VIC, 28 years old, earning $85k PAYG full-time. She has $45k savings, $450k borrowing capacity, and a $28k HECS debt. No existing properties. Her goal is to buy her first investment property within 12 months. She has a moderate risk tolerance with a 10+ year horizon but is unsure on strategy - needs guidance on whether to pursue growth or cash flow. No broker, no accountant, no pre-approval yet. Her biggest challenge is knowing where to start.',
        finderFred: 'Sarah is looking to buy her first investment property within the next 6-12 months. Budget is around $450k based on borrowing capacity. She has $45k cash for deposit. Based in VIC but open to interstate for the right deal. Prefers metro and major regional areas. No strategy preference yet - needs guidance on property type and location. No existing portfolio. PAYG on $85k, moderate risk tolerance.',
        investorCoach: 'Sarah earns $85k/year PAYG full-time, 3 years in role. No existing properties - this will be her first investment purchase. $45k cash savings, $4,600/month expenses. $28k HECS debt reducing borrowing capacity. Total borrowing capacity $450k. No broker or pre-approval yet. $5k credit card limit. No other income streams. Goal is to build a portfolio over 10+ years starting with first purchase in the next 12 months. Moderate risk tolerance, unsure on growth vs cash flow strategy.',
        dealSpecialist: 'Sarah has no existing ownership structures - no trusts, companies, or SMSF. She is on the 32.5% marginal tax rate ($85k income). No accountant or solicitor engaged. No financial planner. This is her first property purchase so structure decisions are being made from scratch. No dependents, not investing with a partner. No insurance considerations yet as no portfolio exists.',
      },
      completenessScore: 78,
      dataGaps: ['partnerIncome', 'otherIncomeStreams', 'hasFinancialPlanner', 'interestedInStructuring'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'growing-portfolio',
    label: 'James - Growing Portfolio',
    description: '2 properties, $180k equity, scaling up',
    profile: {
      personal: {
        firstName: 'James',
        age: 35,
        state: 'VIC',
        dependents: 2,
        partnerInvesting: true,
        partnerIncome: 75000,
      },
      employment: {
        grossAnnualIncome: 130000,
        employmentType: 'payg-fulltime',
        yearsInRole: 6,
        hasHecsHelp: true,
        hecsBalance: 12000,
        otherIncomeStreams: 'Rental income from 2 investment properties',
        otherIncomeAmount: 54000,
      },
      financial: {
        cashSavings: 85000,
        monthlyExpenses: 6500,
        existingDebts: [
          { type: 'hecs', balance: 12000 },
          { type: 'car-loan', balance: 18000, monthlyRepayment: 450 },
        ],
        borrowingCapacity: 720000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 15000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 850000,
        homeMortgage: 520000,
        investmentProperties: [
          {
            location: 'Brunswick, VIC',
            type: 'unit-apartment',
            currentValue: 620000,
            mortgageOwing: 480000,
            weeklyRent: 520,
            ownershipStructure: 'personal',
            yearPurchased: 2021,
            purchasePrice: 545000,
          },
          {
            location: 'Geelong, VIC',
            type: 'house',
            currentValue: 485000,
            mortgageOwing: 390000,
            weeklyRent: 410,
            ownershipStructure: 'joint-personal',
            yearPurchased: 2023,
            purchasePrice: 460000,
          },
        ],
        totalEquity: 180000,
      },
      goals: {
        primaryGoal: 'grow-portfolio',
        goalDetail: 'Scale to 5 properties in the next 3 years using equity recycling',
        timeHorizon: '3-5-years',
        riskTolerance: 'growth',
        strategyPreference: 'capital-growth',
        nextStepTimeline: 'Next 6 months',
        budgetForNextPurchase: 550000,
      },
      locationPrefs: {
        preferredStates: ['VIC', 'QLD'],
        preferredRegions: ['South-east QLD', 'Geelong corridor'],
        openToInterstate: true,
        proximityPreference: 'Metro and major regional',
      },
      taxAndStructure: {
        marginalTaxRate: '37',
        hasAccountant: true,
        hasSolicitor: false,
        existingStructures: ['personal', 'joint-personal'],
        interestedInStructuring: true,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 3,
        biggestChallenge: 'Not sure how to access equity without selling',
        specificQuestionsForToday: 'Want to understand trust structures for future acquisitions',
      },
      summary: 'James is a 35-year-old investor based in Victoria with 2 investment properties and a PPOR. He earns $130k PAYG plus $75k from his partner, with $54k rental income. He has $180k usable equity, $85k cash, and $720k borrowing capacity. Properties are held in personal and joint names - he is interested in moving to trust structures. His goal is to scale to 5 properties within 3 years using equity recycling, targeting capital growth in VIC and QLD. He has a broker and accountant but no solicitor.',
      agentBriefs: {
        baselineBen: 'James is 35, based in VIC, with 2 investment properties plus a PPOR. He earns $130k PAYG (partner $75k), has $180k usable equity and $720k borrowing capacity. Goal is to scale from 2 to 5 properties in 3 years via equity recycling, focusing on capital growth. He has 3 years of investing experience but is unsure how to access equity without selling. He wants to explore trust structures for future purchases. Has a broker and accountant. Growth-oriented risk tolerance. 2 dependents.',
        finderFred: 'James is looking to buy his next property within 6 months, budget around $550k. He has $85k cash and $180k usable equity across his portfolio. Prefers VIC and QLD - specifically the Geelong corridor and south-east QLD. Open to interstate. Strategy is capital growth focused. Currently has a unit in Brunswick and a house in Geelong. Looking for his 3rd investment property on the path to 5 total. Has a broker. PAYG on $130k plus partner income of $75k.',
        investorCoach: 'James earns $130k/year PAYG, 6 years in role. Partner earns $75k and co-invests. PPOR worth $850k with $520k mortgage. Investment property 1: Brunswick unit, $620k value, $480k owing, $520/wk rent, personal name, bought 2021 for $545k. Investment property 2: Geelong house, $485k value, $390k owing, $410/wk rent, joint names, bought 2023 for $460k. Total equity ~$180k. Borrowing capacity $720k. $85k cash. $12k HECS, $18k car loan ($450/mo), $15k credit card limits. $6,500/mo expenses. 2 dependents. Goal: scale to 5 properties in 3 years via equity recycling, capital growth strategy.',
        dealSpecialist: 'James holds properties in personal name (Brunswick unit) and joint-personal name with partner (Geelong house). PPOR in joint names. No trusts or companies set up but actively interested in structuring future acquisitions through trusts. Marginal tax rate 37% ($130k + $54k rental). Has an accountant. No solicitor. No financial planner. No SMSF. 2 dependents. Partner co-invests. Looking at 3+ more purchases over 3 years so structure decisions are urgent.',
      },
      completenessScore: 92,
      dataGaps: ['hasFinancialPlanner', 'hasInsurance'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'high-equity',
    label: 'Karen - High Equity',
    description: '4 properties, $620k equity, looking at development',
    profile: {
      personal: {
        firstName: 'Karen',
        age: 45,
        state: 'QLD',
        dependents: 1,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 175000,
        employmentType: 'self-employed-company',
        yearsInRole: 12,
        hasHecsHelp: false,
        otherIncomeStreams: 'Share dividends, rental income from 4 properties',
        otherIncomeAmount: 95000,
      },
      financial: {
        cashSavings: 220000,
        monthlyExpenses: 7900,
        existingDebts: [],
        borrowingCapacity: 1200000,
        hasBroker: true,
        hasPreApproval: true,
        creditCardLimits: 30000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 1100000,
        homeMortgage: 280000,
        investmentProperties: [
          {
            location: 'Newstead, QLD',
            type: 'unit-apartment',
            currentValue: 580000,
            mortgageOwing: 320000,
            weeklyRent: 550,
            ownershipStructure: 'family-trust',
            yearPurchased: 2017,
            purchasePrice: 420000,
          },
          {
            location: 'Cannon Hill, QLD',
            type: 'house',
            currentValue: 780000,
            mortgageOwing: 450000,
            weeklyRent: 580,
            ownershipStructure: 'family-trust',
            yearPurchased: 2019,
            purchasePrice: 590000,
          },
          {
            location: 'Logan, QLD',
            type: 'duplex',
            currentValue: 620000,
            mortgageOwing: 400000,
            weeklyRent: 680,
            ownershipStructure: 'family-trust',
            yearPurchased: 2020,
            purchasePrice: 485000,
          },
          {
            location: 'Ipswich, QLD',
            type: 'house',
            currentValue: 450000,
            mortgageOwing: 340000,
            weeklyRent: 420,
            ownershipStructure: 'personal',
            yearPurchased: 2022,
            purchasePrice: 380000,
          },
        ],
        totalEquity: 620000,
      },
      goals: {
        primaryGoal: 'development',
        goalDetail: 'Explore subdivision and development opportunities to accelerate wealth',
        timeHorizon: '3-5-years',
        riskTolerance: 'aggressive',
        strategyPreference: 'value-add',
        nextStepTimeline: 'Next 3 months',
        budgetForNextPurchase: 800000,
      },
      locationPrefs: {
        preferredStates: ['QLD'],
        preferredRegions: ['Brisbane metro', 'Gold Coast corridor'],
        openToInterstate: false,
        proximityPreference: 'Metro only',
      },
      taxAndStructure: {
        marginalTaxRate: '45',
        hasAccountant: true,
        hasSolicitor: true,
        hasFinancialPlanner: true,
        existingStructures: ['family-trust', 'personal'],
        interestedInStructuring: false,
        hasSMSF: true,
        smsfBalance: 380000,
      },
      experience: {
        investingExperience: 'experienced',
        yearsInvesting: 8,
        biggestChallenge: 'Finding development-grade sites with the right zoning',
        specificQuestionsForToday: 'How to structure a subdivision JV',
      },
      summary: 'Karen is a 45-year-old experienced investor based in QLD, running her own company earning $175k plus $95k from investments. She has 4 investment properties plus a PPOR, with $620k usable equity and $1.2M borrowing capacity. Most properties held in a family trust, one in personal name. She has a full advisory team (accountant, solicitor, financial planner) and a $380k SMSF. Her focus is now on development and subdivision - she wants to find development sites in Brisbane metro within the next 3 months. Aggressive risk tolerance.',
      agentBriefs: {
        baselineBen: 'Karen is an experienced investor (8 years, 4 properties) based in QLD. Self-employed through her own company, earning $175k + $95k investment income. $620k equity, $1.2M borrowing capacity, $220k cash. She has moved past buy-and-hold and wants to pursue subdivision and development in Brisbane metro. Full advisory team in place. Family trust structures established. SMSF with $380k. 1 dependent. Her challenge is finding the right development sites with appropriate zoning. Aggressive risk tolerance, 3-5 year active strategy.',
        finderFred: 'Karen is looking for development-grade sites in Brisbane metro and Gold Coast corridor, budget up to $800k. She wants to move within 3 months - has pre-approval and $220k cash plus $620k equity. Not open to interstate. Metro locations only. She already owns in Newstead, Cannon Hill, Logan, and Ipswich. Strategy is value-add/development, specifically subdivision. She has 8 years experience and a broker. Self-employed on $175k.',
        investorCoach: 'Karen earns $175k self-employed (Pty Ltd), 12 years running. $95k additional income from shares and rent. PPOR worth $1.1M with $280k owing. Property 1: Newstead unit, $580k value, $320k owing, $550/wk rent, family trust, bought 2017. Property 2: Cannon Hill house, $780k value, $450k owing, $580/wk, family trust, bought 2019. Property 3: Logan duplex, $620k value, $400k owing, $680/wk, family trust, bought 2020. Property 4: Ipswich house, $450k value, $340k owing, $420/wk, personal name, bought 2022. Total equity $620k. Borrowing capacity $1.2M. $220k cash. $7,900/mo expenses. No debts outside mortgages. $30k credit card limits. Pre-approved. Goal: development and subdivision.',
        dealSpecialist: 'Karen has a family trust holding 3 of 4 investment properties (Newstead, Cannon Hill, Logan). Ipswich property in personal name. PPOR in personal name. Marginal tax rate 45% ($175k + $95k investment income). Full advisory team: accountant, solicitor, financial planner. SMSF with $380k balance. Not looking for new structures - existing trust setup works well. 1 dependent. Interested in structuring a subdivision JV. Self-employed through Pty Ltd, 12 years.',
      },
      completenessScore: 95,
      dataGaps: ['hecsBalance', 'partnerIncome'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'cash-flow-focused',
    label: 'Mike - Cash Flow Focused',
    description: '1 property, wants passive income',
    profile: {
      personal: {
        firstName: 'Mike',
        age: 52,
        state: 'SA',
        dependents: 0,
        partnerInvesting: false,
      },
      employment: {
        grossAnnualIncome: 95000,
        employmentType: 'payg-fulltime',
        yearsInRole: 15,
        hasHecsHelp: false,
      },
      financial: {
        cashSavings: 60000,
        monthlyExpenses: 5200,
        existingDebts: [],
        borrowingCapacity: 520000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 8000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 550000,
        homeMortgage: 180000,
        investmentProperties: [
          {
            location: 'Elizabeth, SA',
            type: 'house',
            currentValue: 380000,
            mortgageOwing: 260000,
            weeklyRent: 370,
            ownershipStructure: 'personal',
            yearPurchased: 2020,
            purchasePrice: 295000,
          },
        ],
        totalEquity: 85000,
      },
      goals: {
        primaryGoal: 'passive-income',
        goalDetail: 'Build passive rental income to replace salary within 15 years',
        timeHorizon: '10-plus-years',
        riskTolerance: 'conservative',
        strategyPreference: 'cash-flow',
        nextStepTimeline: 'Next 12 months',
        budgetForNextPurchase: 400000,
      },
      locationPrefs: {
        preferredStates: ['SA', 'QLD'],
        openToInterstate: true,
        preferredRegions: ['Adelaide metro', 'Regional QLD'],
        proximityPreference: 'Happy with regional',
      },
      taxAndStructure: {
        marginalTaxRate: '32.5',
        hasAccountant: true,
        hasSolicitor: false,
        existingStructures: ['personal'],
        interestedInStructuring: false,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 4,
        biggestChallenge: 'Finding cash-flow-positive properties in the current market',
      },
      summary: 'Mike is a 52-year-old conservative investor based in South Australia, earning $95k PAYG. He has 1 investment property (Elizabeth, SA) plus a PPOR, with $85k usable equity and $520k borrowing capacity. His focus is building passive rental income to replace his salary within 15 years. He prefers cash-flow-positive properties and is open to SA and QLD including regional areas. Has a broker and accountant. $60k cash. No dependents, no partner co-investing.',
      agentBriefs: {
        baselineBen: 'Mike is 52, based in SA, conservative investor with a 15-year plan to replace his $95k salary with passive rental income. Has 1 investment property in Elizabeth SA plus a PPOR. $85k equity, $520k borrowing, $60k cash. 4 years experience. Cash-flow strategy. His challenge is finding properties that are actually cash-flow positive in the current market. Has a broker and accountant. No dependents, not investing with a partner. Needs a realistic roadmap to hit his income replacement goal.',
        finderFred: 'Mike is looking for his 2nd investment property within the next 12 months. Budget around $400k. Cash-flow strategy - must be cash-flow positive or very close to it. Open to SA (Adelaide metro) and QLD (regional). Happy with regional areas. Has $60k cash and $85k equity. Has a broker. Currently owns in Elizabeth, SA. PAYG on $95k, conservative risk tolerance. Prefers houses based on current portfolio.',
        investorCoach: 'Mike earns $95k/year PAYG, 15 years in role. No HECS, no other debts. PPOR worth $550k with $180k owing. Investment property: Elizabeth SA house, $380k value, $260k owing, $370/wk rent, personal name, bought 2020 for $295k. Total equity $85k. Borrowing capacity $520k. $60k cash. $5,200/mo expenses. $8k credit card limits. No dependents. Goal: build passive income stream to replace salary in 15 years. Conservative risk tolerance, cash-flow focused. Needs to model how many properties and what yield to hit his target.',
        dealSpecialist: 'Mike holds his investment property and PPOR in personal name. No trusts, companies, or SMSF. Not interested in restructuring at this stage. Marginal tax rate 32.5% ($95k income). Has an accountant. No solicitor or financial planner. No dependents, not investing with a partner. Conservative approach - asset protection is less of a concern given small portfolio. May need to revisit structures as portfolio grows.',
      },
      completenessScore: 82,
      dataGaps: ['age', 'otherIncomeStreams', 'hasFinancialPlanner', 'smsfBalance'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
  {
    id: 'asset-protection',
    label: 'Linda - Structure & Protection',
    description: '3 properties, needs trust/company structures',
    profile: {
      personal: {
        firstName: 'Linda',
        age: 41,
        state: 'NSW',
        dependents: 3,
        partnerInvesting: true,
        partnerIncome: 120000,
      },
      employment: {
        grossAnnualIncome: 210000,
        employmentType: 'payg-fulltime',
        yearsInRole: 8,
        hasHecsHelp: false,
        otherIncomeStreams: 'Rental income from 3 properties, partner income',
        otherIncomeAmount: 78000,
      },
      financial: {
        cashSavings: 150000,
        monthlyExpenses: 10000,
        existingDebts: [
          { type: 'car-loan', balance: 25000, monthlyRepayment: 600 },
        ],
        borrowingCapacity: 950000,
        hasBroker: true,
        hasPreApproval: false,
        creditCardLimits: 20000,
      },
      portfolio: {
        ownsHome: true,
        homeValue: 1400000,
        homeMortgage: 650000,
        investmentProperties: [
          {
            location: 'Parramatta, NSW',
            type: 'unit-apartment',
            currentValue: 650000,
            mortgageOwing: 480000,
            weeklyRent: 520,
            ownershipStructure: 'personal',
            yearPurchased: 2018,
            purchasePrice: 530000,
          },
          {
            location: 'Newcastle, NSW',
            type: 'house',
            currentValue: 720000,
            mortgageOwing: 520000,
            weeklyRent: 560,
            ownershipStructure: 'joint-personal',
            yearPurchased: 2020,
            purchasePrice: 580000,
          },
          {
            location: 'Wollongong, NSW',
            type: 'townhouse',
            currentValue: 580000,
            mortgageOwing: 430000,
            weeklyRent: 480,
            ownershipStructure: 'personal',
            yearPurchased: 2022,
            purchasePrice: 520000,
          },
        ],
        totalEquity: 450000,
      },
      goals: {
        primaryGoal: 'restructure',
        goalDetail: 'Restructure holdings into trusts and optimise tax position',
        timeHorizon: '5-10-years',
        riskTolerance: 'moderate',
        strategyPreference: 'balanced',
        nextStepTimeline: 'Next 3-6 months',
        budgetForNextPurchase: 700000,
      },
      locationPrefs: {
        preferredStates: ['NSW', 'QLD'],
        openToInterstate: true,
        preferredRegions: ['Sydney metro', 'Central Coast', 'South-east QLD'],
      },
      taxAndStructure: {
        marginalTaxRate: '45',
        hasAccountant: true,
        hasSolicitor: false,
        hasFinancialPlanner: false,
        existingStructures: ['personal', 'joint-personal'],
        interestedInStructuring: true,
        hasSMSF: false,
      },
      experience: {
        investingExperience: 'novice-investor',
        yearsInvesting: 6,
        biggestChallenge: 'Properties all in personal names, paying too much tax, worried about asset protection',
        specificQuestionsForToday: 'How to move existing properties into trust structures',
      },
      summary: 'Linda is a 41-year-old investor based in NSW earning $210k plus $120k from her partner. She has 3 investment properties plus a PPOR, all held in personal or joint-personal names. $450k equity, $950k borrowing capacity, $150k cash. Her primary concern is restructuring into trusts for asset protection and tax optimisation - she is on the 45% marginal rate and feels she is paying too much tax. Has an accountant but no solicitor or financial planner. 3 dependents. Partner co-invests. 6 years experience.',
      agentBriefs: {
        baselineBen: 'Linda is 41, based in NSW, earning $210k (partner $120k). 3 investment properties plus PPOR, all in personal/joint names. $450k equity, $950k borrowing, $150k cash. 6 years experience but still a novice in structures. Her top priority is restructuring into trusts for asset protection and tax optimisation - she is on the 45% rate and feels overexposed. Has a broker and accountant but no solicitor. 3 dependents. Moderate risk tolerance, balanced strategy. Wants to continue growing the portfolio while fixing the structural issues.',
        finderFred: 'Linda is looking to buy her 4th investment property within 3-6 months, budget around $700k. Prefers NSW (Sydney metro, Central Coast) and south-east QLD. Open to interstate. Has $150k cash and $450k equity. Balanced strategy - mix of growth and cash flow. Currently owns in Parramatta, Newcastle, and Wollongong. Has a broker. PAYG on $210k plus partner $120k. Moderate risk tolerance. Note: she is in the process of restructuring so new purchases may need to go into a trust.',
        investorCoach: 'Linda earns $210k/year PAYG, 8 years in role. Partner earns $120k and co-invests. PPOR worth $1.4M with $650k owing. Property 1: Parramatta unit, $650k value, $480k owing, $520/wk rent, personal name, bought 2018 for $530k. Property 2: Newcastle house, $720k value, $520k owing, $560/wk, joint names, bought 2020 for $580k. Property 3: Wollongong townhouse, $580k value, $430k owing, $480/wk, personal name, bought 2022 for $520k. Total equity $450k. Borrowing capacity $950k. $150k cash. $25k car loan ($600/mo). $10k/mo expenses. $20k credit card limits. 3 dependents. Goal: restructure for tax and protection while continuing to grow. Balanced strategy.',
        dealSpecialist: 'Linda holds all properties in personal or joint-personal names - no trusts, companies, or SMSF. This is her primary pain point. She wants to restructure into trust structures for asset protection and tax optimisation. Marginal tax rate 45% ($210k + $78k rental income). Has an accountant but NO solicitor or financial planner - will need both for restructuring. 3 dependents. Partner co-invests ($120k income). Key question: how to move existing properties into trusts (stamp duty implications, CGT triggers). Portfolio: Parramatta (personal), Newcastle (joint), Wollongong (personal). 6 years investing experience.',
      },
      completenessScore: 88,
      dataGaps: ['proximityPreference', 'smsfBalance', 'yearsInvesting'],
      collectedAt: '2026-01-31T00:00:00.000Z',
    },
  },
];
